# Generated by Django 5.0.6 on 2024-06-26 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_Arquitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Arquitectura', max_length=255)),
                ('desing', models.CharField(choices=[('Digitalización', 'Digitalización'), ('Levantamiento', 'Levantamiento'), ('Adecuación', 'Adecuación')], max_length=255)),
                ('architectural_proposal', models.CharField(choices=[('Planos De Arquitectura', 'Planos De Arquitectura'), ('Diseño Interior', 'Diseño Interior'), ('Modelacion 3d', 'Modelacion 3d'), ('Inspección De Obras', 'Inspección De Obras')], max_length=255)),
                ('others', models.TextField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_arquitecture_business', to='administrator.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_arquitecture', to='administrator.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Services_Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Impresion', max_length=255)),
                ('amount', models.IntegerField(default=1)),
                ('formats', models.CharField(choices=[('Rollo Bond x Mt', 'Rollo Bond x Mt'), ('Lamina Bond', 'Lamina Bond'), ('Media Lamina Bond', 'Media Lamina Bond'), ('Tabloide', 'Tabloide'), ('Oficio', 'Oficio'), ('Carta', 'Carta')], max_length=255)),
                ('type_of_paper', models.CharField(choices=[('Papel Bond', 'Papel Bond'), ('Papel Glasse', 'Papel Glasse'), ('Opalina', 'Opalina')], max_length=255)),
                ('color', models.CharField(choices=[('Blanco Y Negro', 'Blanco Y Negro'), ('Full Color', 'Full Color'), ('Escala De Grises', 'Escala De Grises')], max_length=255)),
                ('others', models.TextField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_impression_business', to='administrator.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_impression', to='administrator.customer')),
            ],
        ),
    ]
